### ISSUE TITLE
db files will be depercated in sing-box

### ISSUE THREAD

**Issue by OBrein** [L11R/antizapret-sing-box-geo#3]
In the new version of sing-box 1.8, support for db files has been marked as deprecated. Now they are implementing the use of src, as in Clash. Is it possible to modify the script for new src files?
https://sing-box.sagernet.org/migration/#migrate-geosite-to-rule-sets

**Comment by L11R** [comment]
@OBrein I added support for Rule Sets. Can someone please test? I am no longer live in Russia.

**Comment by L11R** [comment]
@turikhay, @piezoelement, @stllfe, @xtropi, @omgiafs, @gersoctruda mention you because you liked the original idea, would like to get a feedback!

**Comment by turikhay** [comment]
LGTM, seems to be working OK
